### PR TITLE
Perl review, Week 052

### PR DESCRIPTION
**Pull request by rjt-pl**

### CODE REVIEW

**Comment by rjt-pl** [comment]
Mohammad, I snuck in some CSS tweaks. You may want to have a look at them before merging. I've made changes to hr, lists, and some font size tweaks for inline (not block) code.

**Comment by rjt-pl** [comment]
Can this be merged/published now? It's been a rough few weeks for me, so it was not easy getting caught back up and getting this review done on time. 053 is almost done, too.

**Comment by manwar** [comment]
Apology for the delay, I was supposed to do first thing in the morning. I was then distracted doing some urgent production issues.

**Comment by rjt-pl** [comment]
No worries, Mohammad. Sorry for the nag, and thanks for the merge!

**Comment by manwar** [comment]
It is now live :-)
https://perlweeklychallenge.org/blog/review-challenge-052

**Pull request merged**
